name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
  # sunday 9AM
    - cron: "00 9 * * 0"
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/links.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        continue-on-error: true

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          token: ${{secrets.GITHUB_TOKEN}}